### ISSUE TITLE
Is there a fallback build instead of wasm? 

### ISSUE THREAD

**Issue by chendatony31** [bitcoinjs/tiny-secp256k1#109]
I want the js can be compatible with most browsers even old ones. Is there a fallback build instead of wasm?

**Comment by FlorianHubl** [comment]
Anything new on this?

**Comment by landabaso** [comment]
Use previous 1.* version of tiny-secp256k1.
I also maintain this npm package "@bitcoinerlab/secp256k1" based on Paul Miller's Noble that does not require wasm.

**Comment by chendatony31** [comment]
> Use previous 1.* version of tiny-secp256k1. I also maintain this npm package "@bitcoinerlab/secp256k1" based on Paul Miller's Noble that does not require wasm.

Yes, using `@noble/secp256k1` to implement ecc's functions is a way. 👍

**Comment by akriafly** [comment]
I can't understand why this lib uses WASM.

**Comment by junderw** [comment]
`@bitcoinerlab/secp256k1` which is maintained by @landabaso is a good alternative.

I am also considering using wasm2js to generate an asm.js (pure JS) based mirror package in the future.

`@bitcoinerlab/secp256k1` should be more performance than the asm.js version, though.

That said. React Native now supports WASM. Try convincing your teams to update your react versions to a more recent one so you don't have to deal with these problems anymore.
