### ISSUE TITLE
Does this implement deterministic k generation

### ISSUE THREAD

**Issue by abdurahmanshiine** [bitcoinjs/tiny-secp256k1#110]
Hi there,

I found out that bitcoinJS-lib uses this library to generate the k parameter for transaction signatures and they mentioned that because of how JS works; this could end up generating similar k values at times.

So I was wondering if this supports deterministic k generation which could perhaps avoid fix that issue, and if not then what are the reasons?

**Comment by junderw** [comment]
RFC6979 support (deterministic K generation) has been in bitcoinJS and this library for a very, very long time.

Unless you're using v2 or v1 from 2014 or something, you should be fine.

**Comment by abdurahmanshiine** [comment]
Thanks for the clarification
