### ISSUE TITLE
What is the difference between 'secp256k1' and 'ecurve'

### ISSUE THREAD

**Issue by JQiMeng** [bitcoinjs/tiny-secp256k1#12]
thank your work !! and i want to know the difference of the '**secp256k1**' and '**ecurve**'
```
 try {
   module.exports = require('bindings')('secp256k1')
 } catch (err) {
   module.exports = require('./ecurve')
 }
```

**Comment by dcousens** [comment]
https://github.com/cryptocoinjs/ecurve
https://github.com/bitcoin-core/secp256k1
