### ISSUE TITLE
Cant figure equivalents to `bcrypto.secp256k1` calls

### ISSUE THREAD

**Issue by Overtorment** [bitcoinjs/tiny-secp256k1#120]
Specifically, I need equivalents for 

* `privateKeyTweakMul()`
* `publicKeyTweakMul()`
* `publicKeyCombine()`
* `privateKeyTweakAdd()`
* `privateKeyNegate()`

currently using  `const sec = require("bcrypto").secp256k1;`  for these, but want to switch either to `tiny` or to `noble`ecc (which is afaik has similar set of methods)

**Comment by junderw** [comment]
I know https://www.npmjs.com/package/secp256k1 supports these as well (including JS for browsers)

It would be trivial to add these methods... but the whole point of the `tiny-secp256k1` library is to have a tiny interface and not pull in every single function from libsecp256k1.

What are those methods for? A new feature in BW?

**Comment by junderw** [comment]
Or maybe those are already in tiny...

Let me check.

**Comment by junderw** [comment]
privateKeyTweakMul -> no
publicKeyTweakMul -> pointMultiply
publicKeyCombine -> pointAdd (but tiny can only combine 2 keys at a time)
privateKeyTweakAdd -> privateAdd
privateKeyNegate -> privateNegate

**Comment by junderw** [comment]
So the question would be:

1. Why do you need privateKeyTweakMul?
2. Do you need to combine 3 or more pubkeys all at once? If so, why?

**Comment by Overtorment** [comment]
that helped, thanks!
implemented here: https://github.com/Overtorment/SilentPayments/pull/5
