### ISSUE TITLE
import tiny-secp256k1 in browser causes TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute

### ISSUE THREAD

**Issue by bomzj** [bitcoinjs/tiny-secp256k1#129]
The following line causes crash in browser environment while working in Node.
```js
import * as ecc from 'tiny-secp256k1'
```

Note: tiny-secp256k1 version is 2.2.3.

**Comment by junderw** [comment]
Try 'tiny-secp256ka-asmjs' package for browser environments.

**Comment by bomzj** [comment]
@junderw thank you for pointing out!

Just wondering should one use 'tiny-secp256k1-asmjs' for just one thing to generate bitcoin private key only? Is it an overkill for that purpose?

My assumption is that I can use `window.crypto.getRandomValues` instead
```js
const privateKeyBytes = new Uint8Array(32)
window.crypto.getRandomValues(privateKeyBytes)
```
But I'm not sure how reliable it is. 

What would you suggest in this case?
