### ISSUE TITLE
how can i decode the signature to hash by public key ?

### ISSUE THREAD

**Issue by jojoin** [bitcoinjs/tiny-secp256k1#13]
I want to develop and implement a feature: using private key serial signature, get a final signature string, and then verify it use public key list in sequence.

Can I get your help ？

**Comment by dcousens** [comment]
Trying to understand what you're actually after here,  but it seems:

* Using a private key,  sign a message
* Using a public key, verify that message

Is that all?

**Comment by jojoin** [comment]
No, I mean:

- Using a private key, encode a message
- Using a public key, **decode** the message

I didn't find the way to decrypt it. Didn't it support?

**Comment by dcousens** [comment]
Ah,  this library doesn't support ECDH like-encryption utilities or tools.  It is highly focused for usage in `bitcoinjs-lib`.

You might be able to use https://github.com/cryptocoinjs/secp256k1-node/blob/master/API.md#ecdhbuffer-publickey-buffer-privatekey---buffer instead.

@fanatid ?

**Comment by jojoin** [comment]
very thanks !

**Comment by fanatid** [comment]
@dcousens no, ECDH only about creating shared secret from 2 private keys without disclosing keys to each other with Elliptic Curves.
I can not remember anything what used private key for encrypting and public for decrypting.
