### ISSUE TITLE
Feature Request: Support for private key multiply

### ISSUE THREAD

**Issue by rbndg** [bitcoinjs/tiny-secp256k1#138]
Is it possible to add support `secp256k1_ec_seckey_tweak_mul`?
There is support for pub key multiply but not private key multiply

**Comment by junderw** [comment]
What is the use case?

The point of tiny-secp256k1 is to be a smaller interface than node-secp256k1.

Specifically, only the functions necessary to create Bitcoin applications. (BitcoinJS)

**Comment by rbndg** [comment]
yes, that's fair enough.
