### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by discofiend** [bitcoinjs/tiny-secp256k1#14]
> WARNING in ./node_modules/bindings/bindings.js 81:43-53
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/tiny-secp256k1/index.js
 @ ./node_modules/bip32/index.js
 @ ./node_modules/oip-hdmw/lib/Coin.js
 @ ./node_modules/oip-hdmw/lib/index.js
 @ ./node_modules/oip-account/lib/Account.js
 @ ./node_modules/oip-account/lib/index.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://127.0.0.1:9156 ./src/index.js

Is there anything wrong in this export? 

```
//tiny-secp256k1/index.js
'use strict'

try 
  module.exports = require('bindings')('secp256k1')
} catch (err) {
  module.exports = require('./ecurve')
}
```

**Comment by fanatid** [comment]
@dcousens looks like you need add `browser` field to package.json

**Comment by dcousens** [comment]
Resolved in https://github.com/bitcoinjs/tiny-secp256k1/pull/15
