### ISSUE TITLE
Npm missing description

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/tiny-secp256k1#24]

**Comment by miketwenty1** [comment]
I'm very confused about this NPM package. Why does it fail to show up on runkit? is it possible this has something to do with it?
https://npm.runkit.com/tiny-secp256k1
Runkit seems to have everything else except this npm package.

**Comment by miketwenty1** [comment]
Unfortunately that didn't seem to solve what ever hangup Runkit is having with this package... I have no idea.. it's just frustrating to demo Bitcoinjs this way and having to go back to v3.x.x

**Comment by dcousens** [comment]
@miketwenty1 what exactly is the error you get?

**Comment by miketwenty1** [comment]
I'm not getting an error. Runkit is failing to find the package for some reason. I'm just confused about it.
![screen shot 2018-09-15 at 3 57 21 am](https://user-images.githubusercontent.com/7761473/45584086-9855c680-b89b-11e8-91ef-e7b61269870d.png)

**Comment by dcousens** [comment]
Report it as missing then?
Why is that a problem with this package?

**Comment by miketwenty1** [comment]
To be Honest I'm not sure if there is a problem with this package or not. I've reported it missing here and there for the last couple weeks.. nothing has come of it. 

I just found it weird as npm's main page practically now has runkit built into it, (You would think it would be reliable). Hence my original confusion about this.. and even more confusion.. the parent "bigger" package is easily found by runkit.  Feel free to close this, I was just here to watch a miracle happen if you added a description.

**Comment by dcousens** [comment]
@miketwenty1 the description hasn't been added yet,  wait for the PR to be merged + released

**Comment by dcousens** [comment]
@miketwenty1 check in a few minutes,  I'll be happy for you if it fixed :+1:

**Comment by miketwenty1** [comment]
didn't seem to fix anything :( 
Posted here: 
https://discuss.runkit.com/t/whoops-should-we-have-tiny-secp256k1-yes-please/1133

Hopefully they can figure it out.
