### ISSUE TITLE
Re-introduce privateKeyNegate

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/tiny-secp256k1#61]
It was not needed pre-taproot... but since it looks like we will need to negate private keys a lot when they are odd-y (0x03) pubkeys, this is probably needed moving forward.

**Comment by junderw** [comment]
I'm thinking this should maybe be done at a lower level:

https://github.com/bitcoin-core/secp256k1/issues/1015

**Comment by junderw** [comment]
Since it seems like bitcoin-core/secp256k1#1015 is DOA maybe we should move forward with this. @motorina0

**Comment by motorina0** [comment]
Done. See commit: https://github.com/bitcoinjs/tiny-secp256k1/pull/69/commits/b79dcf4aa03d18d8a18aa36b35ad2647386a3adc

Hmm, maybe it should have been on a new branch.
