### ISSUE TITLE
tiny-secp256k1 fails to build on Apple Silicon

### ISSUE THREAD

**Issue by edoubledy** [bitcoinjs/tiny-secp256k1#67]
Hey! I'm getting build errors on a project that uses `tiny-secp256k1` on an M1 Pro MacBook when the project is built with yarn. The only error is helpfully `tiny-secp256k1Killed`.

**Comment by junderw** [comment]
Please be more specific.

Post logs. Post versions. Post anything else.

This information is not helpful to me unless you want to send me your computer to Japan :-P
