### ISSUE TITLE
expose recover() function

### ISSUE THREAD

**Issue by motorina0** [bitcoinjs/tiny-secp256k1#68]
- `bitcoin-message` lib is using `secp256k1.recover()`
- this function is not exposed by `tiny-secp256k1`

Related discussion: https://github.com/bitcoinjs/ecpair/issues/3#issuecomment-994129267

```
 function verify (message,...
    ...
    const publicKey = secp256k1.recover(
      hash,
      parsed.signature,
      parsed.recovery,
      parsed.compressed
    )
```

**Comment by junderw** [comment]
I remember back when tiny-secp256k1 first started, `bitcoin-message` was brought up.

The reality is: the message signing from Bitcoin Core early versions was never standardized. Many wallets have incompatible methods that are slightly similar, especially in dealing with the various address types. (back then, there was only one address type and the only variance was compressed or not.)

To be honest... bitcoin-message should be archived. At this point any "updates" to it would be meaningless back-end optimizations and arguing minutiae about why we should adopt format X over format Y or how we could make it backwards compatible with format Z (where X Y Z are all different wallet apps that put their own spin on message signing)

Adding recovery just to fill a need for bitcoin-message is not a good reason enough imo.

**Comment by junderw** [comment]
It could be useful for BOLT11 and various Lightning usecases though.

**Comment by motorina0** [comment]
I am trying to have a look at this, but I get a compilation error when running `make`. It's my first time using Rust.

- in `lib.rs` I've added `secp256k1_ecdsa_recover` to `use secp256k1_sys::{...`
- run `make` (using the Docker image):
```
for f in ./lib/cjs/*.cjs; do sed -i -e 's/\(require(".*\)\.js");/\1.cjs");/g' -- "$f"; done
RUSTFLAGS="-C link-args=-zstack-size=655360" cargo build --target wasm32-unknown-unknown --release
    Updating git repository `https://github.com/rust-bitcoin/rust-secp256k1`
    Updating crates.io index
  Downloaded cc v1.0.71
  Downloaded 1 crate (57.5 KB) in 1.29s
   Compiling secp256k1-wasm v0.0.0 (/tiny-secp256k1)
error[E0432]: unresolved import `secp256k1_sys::secp256k1_ecdsa_recover`
  --> src/lib.rs:19:36
   |
19 |     secp256k1_ec_seckey_tweak_add, secp256k1_ecdsa_recover, secp256k1_ecdsa_sign,
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^
   |                                    |
   |                                    no `secp256k1_ecdsa_recover` in the root
   |                                    help: a similar name exists in the module: `secp256k1_ecdsa_verify`

For more information about this error, try `rustc --explain E0432`.
```

I assume the `recovery` module must be `enabled` or something of the sort.
I did add `--enable-module-recovery`  to `util/gen-fixtures/Makefile` but no luck.

**Comment by junderw** [comment]
we'll need to fork rust-secp256k1 since their secp256k1-sys package is a wrapper around the C lib

you will need to add recovery to the build.rs in the sys package.

**Comment by junderw** [comment]
you need to enable the recovery feature in the Cargo.toml file entry for secp256k1-sys

**Comment by junderw** [comment]
```
secp256k1-sys = { version = "0.4.1", default-features = false, features = ["recovery"], git = "https://github.com/rust-bitcoin/rust-secp256k1", rev = "455ee57ba4051bb2cfea5f5f675378170fb42c7f" }
```

should give you a new recovery module to work with.

**Comment by junderw** [comment]
you need to import from the recovery submodule, not the root crate.

**Comment by junderw** [comment]
I am talking about tiny-secp256k1's Cargo.toml btw

**Comment by motorina0** [comment]
> you need to import from the recovery submodule, not the root crate.

Thanks, that was the issue:
`use secp256k1_sys::recovery::{ secp256k1_ecdsa_recover };`

**Comment by motorina0** [comment]
PR merged. https://github.com/bitcoinjs/tiny-secp256k1/pull/69
