### ISSUE TITLE
wasm.memory is undefined

### ISSUE THREAD

**Issue by taylorjdawson** [bitcoinjs/tiny-secp256k1#70]
TypeError: Cannot read properties of undefined (reading 'buffer').

```
const WASM_BUFFER = new Uint8Array(wasm.memory.buffer);
```

at [src_ts/index.ts line 5](https://github.com/bitcoinjs/tiny-secp256k1/blob/40e095e7825db663bbc3cd4950c482a85333e7c4/src_ts/index.ts#L5)

Running this in a create react app with webpack v`5.65.0`

```
webpack: {
    alias: {
      assert: "assert",
      buffer: "buffer",
      crypto: "crypto-browserify",
      http: "stream-http",
      https: "https-browserify",
      os: "os-browserify/browser",
      process: "process/browser",
      stream: "stream-browserify",
      util: "util",
    },
    plugins: {
      add: [
        new webpack.ProvidePlugin({
          process: "process/browser",
          Buffer: ["buffer", "Buffer"],
        }),
      ],
    },
    configure: {
      experiments: {
        asyncWebAssembly: true,
      },
    },
  },
```

Here is the [repo](https://github.com/blocknative/react-demo/tree/feature/o2). If you have a ledger you can repro. Let me know and I can outline steps

**Comment by junderw** [comment]
Please see our example react app:
https://github.com/bitcoinjs/tiny-secp256k1/tree/v2.1.2/examples/react-app

**Comment by taylorjdawson** [comment]
@junderw As you can I already have enabled:
```js
experiments: {
  asyncWebAssembly: true
},
```
And the rest of the settings are essentially the same unless you see that I am missing something in the config.

**Comment by junderw** [comment]
Please ask on the react issues.

This issue tracker is a place to track issues for tiny-secp256k1, and wasm.memory is a well defined part of the WASM spec, and we have it working in an example react app.

Anything beyond this is an issue with React and your configuration/environment. Which we are not equipped to assist you with.

**Comment by classic-k** [comment]
> @junderw As you can see I already have enabled:
> 
> ```js
> experiments: {
>   asyncWebAssembly: true
> },
> ```
> 
> And the rest of the settings are essentially the same unless you see that I am missing something in the config.

Been on this for 2 days even topLevelAwait did not make wasm.memory defined. Kindly share if you have a workaround thank you
