### ISSUE TITLE
Cannot use import statement outside a module when importing this package using Jest

### ISSUE THREAD

**Issue by Robin-Hoodie** [bitcoinjs/tiny-secp256k1#73]
- Follow [the recommended steps to configure Jest to run though Typescript](https://jestjs.io/docs/getting-started#using-typescript)
- Create a file where you create a function that uses an imported function from `"tiny-secp256k1"` 
- Create a spec file where you import the function you created above
- Run `jest` 

This results in the following error

```js
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { compare } from "uint8array-tools";

SyntaxError: Cannot use import statement outside a module

import { pointMultiply, pointAdd } from "tiny-secp256k1";
^
```

It seems the `compare` import from `"uint8array-tools"` is the culprit here

Downgrading to version `1.1.6` resolves the issue

Happy to create a repro or help out if necessary

**Comment by junderw** [comment]
This is a jest configuration issue.

Both this package and uint8array-tools are set to use `require` for node environments and `import` for browser environments.

Most likely setting your jest environment to node should fix the issue.

**Comment by junderw** [comment]
Jest ESM support is a separate issue. Right now it's bundling the MJS code as a CJS.

**Comment by junderw** [comment]
Or maybe it's a babel issue. Assuming you followed that website directions exactly.

**Comment by junderw** [comment]
I work on a private project that uses ts-jest instead of babel and everything works fine, btw.

**Comment by Robin-Hoodie** [comment]
@junderw Here's a repro https://github.com/Robin-hoodie/tiny-secp256k1-repro

**Comment by bufo24** [comment]
I am having the same issue

**Comment by junderw** [comment]
This issue is not with this library. We have used the official NodeJS methods for providing cjs backwards compatibility.

Please follow the issue on the jest repository.

**Comment by junderw** [comment]
https://github.com/facebook/jest/issues/9771#issuecomment-776681032

Try using a custom resolver.

looks like babel also has the same issue.

**Comment by Robin-Hoodie** [comment]
Thanks for the input @junderw , I've been able to "resolve" (pun intended) this now

For anyone experiencing the same problem, here's the TLDR:

Jest currently does not support the `package.json#exports` field (see https://github.com/facebook/jest/issues/9771). Currently Jest plans to add support for it in v28. In case v28 has been released when you're reading this, I'd try just upgrading Jest and see if that resolves the issue.

If v28 has not been released yet or v28 also does not resolve this issue, you can use [the suggestion mentioned here](https://github.com/facebook/jest/issues/9771#issuecomment-841624042)
The complete solution looks as follows:


```js
// jest.config.js
module.exports = {
// other options
  resolver: "<rootDir>/jest-resolver.js"
}

// ./jest-resolver.js
const enhancedResolve = require("enhanced-resolve");

const resolver = enhancedResolve.create.sync({
  conditionNames: ["require", "node", "default", "import"],
  extensions: [".js", ".json", ".node", ".ts"],
});

module.exports = (request, options) => resolver(options.basedir, request);
```

@junderw As I understood, adding a `package.json#main` field would also resolve the issue. Is there a specific reason this has not been added? If you just haven't gotten around to it, let me know and I can create a PR for it.
