### ISSUE TITLE
I want to use this in react-native app but it failed with this error

### ISSUE THREAD

**Issue by Ella-noncelab** [bitcoinjs/tiny-secp256k1#84]
### This is the code snippet I used tiny-secp256k1
![스크린샷 2022-04-25 오후 7 22 26](https://user-images.githubusercontent.com/73803777/165070979-a441c205-6c93-460b-930d-b2a8df8b6f13.png)

-------------------------
### When I run this app, below error occurred.

error: Error: While trying to resolve module `tiny-secp256k1` from file `/Users/eunjilim/AssetController.ts`, the package `/Users/app/node_modules/tiny-secp256k1/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/app/node_modules/tiny-secp256k1/lib/cjs/index.cjs`. Indeed, none of these files exist:

  * /Users/app/node_modules/tiny-secp256k1/lib/cjs/index.cjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * /Users/app/node_modules/tiny-secp256k1/lib/cjs/index.cjs/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
    at DependencyGraph.resolveDependency (/Users/app/node_modules/metro/src/node-haste/DependencyGraph.js:243:17)
    at Object.resolve (/Users/app/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 5)
    at async processModule (/Users/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:198:5)

-----------------------------------------------------------------------
### **and when try to run application this warning show up**

![스크린샷 2022-04-25 오후 7 00 38](https://user-images.githubusercontent.com/73803777/165068809-bb957e61-caa1-42d3-ab19-fac7cf8963f0.png)

**Comment by junderw** [comment]
Probably better to ask this on the metro repo.

**Comment by robhogan** [comment]
Metro maintainer here - thanks @junderw for calling attention to this, it's a known issue on the Metro side. See https://github.com/facebook/metro/issues/815#issuecomment-1117607661 for a workaround.

**Comment by junderw** [comment]
Thanks for the temporary solution and confirmation that the fix is on your radar.

**Comment by niteshbalusu11** [comment]
Thanks guys! Appreciate the help.

**Comment by Ella-noncelab** [comment]
> @Ella-noncelab did you have any luck with this one? I have the same issue.

Sorry.. I just gave up to use this. Because I have to get addresses and keys so I use 'hdkey' package instead. https://www.npmjs.com/package/hdkey

**Comment by landabaso** [comment]
Anyway guys, be aware that `tiny-secp256k1` uses WASM which is not supported by react-native Javascript Core engine (iOS / Android). It does work on react-native-web though. Note that Android emulator may run WASM but it will not run on the actual device.

You can use the older version `tiny-secp256k1@1` (which is quite slow on devices but does the job) or `@noble/secp256k1` which is super fast (order-of-magnitude comparable to WASM) and works together just fine with bitcoinjs-lib.

One last thing. One problem with `@noble/secp256k1` is that it is based on `BigInt`, which is only supported by `iOS` right now, but will also join Android in the upcoming `RN-0.70` release (on the new Hermes Js engine).

**Comment by wookaas** [comment]
> Anyway guys, be aware that `tiny-secp256k1` uses WASM which is not supported by react-native Javascript Core engine (iOS / Android). It does work on react-native-web though. Note that Android emulator may run WASM but it will not run on the actual device.
> 
> You can use the older version `tiny-secp256k1@1` (which is quite slow on devices but does the job) or `@noble/secp256k1` which is super fast (order-of-magnitude comparable to WASM) and works together just fine with bitcoinjs-lib.
> 
> One last thing. One problem with `@noble/secp256k1` is that it is based on `BigInt`, which is only supported in React-Native by `iOS` right now, but will also join Android in the upcoming `RN-0.70` release (using the new Hermes Js engine).

How to replace `tiny-secp256k1` with `@noble/secp256k1`? They have different methods.

**Comment by landabaso** [comment]
> How to replace `tiny-secp256k1` with `@noble/secp256k1`? They have different methods. I want to use it with `bitcoinjs-lib`

Take a look to this npm package: https://github.com/bitcoinerlab/secp256k1.

**Comment by crukundo** [comment]
> > How to replace `tiny-secp256k1` with `@noble/secp256k1`? They have different methods. I want to use it with `bitcoinjs-lib`
> 
> Take a look to this npm package: https://github.com/bitcoinerlab/secp256k1.

This helped. If you are running RN >0.70 with Hermes, this might unblock you.
