### ISSUE TITLE
tiny-secp compilation in swift and java

### ISSUE THREAD

**Issue by mattiaferrari02** [bitcoinjs/tiny-secp256k1#93]
Hi I need to use this library in react-native, but it is tied with wasm that is not supported in react-native environment.
Is it possible to compile your rust source file in java and swift so that it can be called natively from react-native?

The older version of this lib (`1.1.6`) that didn't make use of wasm is no longer usable in my application because one of my deps is calling a method that is implemented only in your newer versions (`privateNegate`)

**Comment by FlorianHubl** [comment]
Anything new on this issue?
