### ISSUE TITLE
Bug when using browserify

### ISSUE THREAD

**Issue by Anderson-Juhasc** [bitcoinjs/tiny-secp256k1#98]
node: v16.18.1
npm: 7.12.0
browserify: v17.0.0

I only run `browserify file.js -o bundle.js` with it:

`const ecc = require('tiny-secp256k1')`

![Screenshot from 2022-12-08 10-42-04](https://user-images.githubusercontent.com/423705/206463494-ca9bedaa-2633-4487-bdd4-11e0383fadaf.png)

**Comment by Anderson-Juhasc** [comment]
I updated the node and npm but got the same error:

node: v19.2.0
npm: 8.19.3

**Comment by vladstarikov88** [comment]
Same for me. I just defined the dependency without any runnin script. And I got this

![image](https://user-images.githubusercontent.com/26491847/221002818-d4ec1474-5c80-44d6-8cf9-f0c2bd82425f.png)

**Comment by junderw** [comment]
Maybe we should stop recommending browserify. It seems like it's not active lately.

Webpack seems to work fine with the new Node exports directive in package.json.
