### ISSUE TITLE
Pure-js backport of `xOnlyPointFromPoint()`..?

### ISSUE THREAD

**Issue by Overtorment** [bitcoinjs/tiny-secp256k1#99]
For a project utilizing ver `1.1.6` Id like to use `xOnlyPointFromPoint()` which is available only on higher versions.
Cant bump`tiny` because it doenst work in my environment (React Native).

`xOnlyPointFromPoint`is needed by BIP47 (payment codes).

Is there any way to hack a pure-js implementation, or backport it to `v1` branch..?

Thanks!

**Comment by junderw** [comment]
It's essentially buffer.slice(1, 33) 🤣

**Comment by junderw** [comment]
xonly pubkey is literally "just take the x value"

**Comment by Overtorment** [comment]
![drake helps](https://user-images.githubusercontent.com/1913337/206899943-e8665f4a-c8f5-4ce9-a576-a65b6ee233e0.gif)

**Comment by Overtorment** [comment]
Found ts implementation https://github.com/bitcoinjs/tiny-secp256k1/blob/8ab242adbb888e43b5964af503b814eadc28f5c5/src_ts/index.ts#L172
I dont know how I overlooked it looking the first time  🤦
